### ISSUE TITLE
ubuntu 怎么实现cmake呢 大佬 

### ISSUE THREAD

**Issue by gittjob** [xiaocao-tian/yolov8_tensorrt#3]
ubuntu 怎么实现cmake呢 大佬

**Comment by FunnyWii** [comment]
我拉了仓库但是还没跑，不过流程和Windows应该是一样的，新建build文件夹，在build下面cmake..&make

**Comment by CoderDoubleTen** [comment]
请问解决了吗？我用ubuntu make的时候报错

**Comment by xiaocao-tian** [comment]
您好，有时间的时候我来处理一下Ubuntu的实现方式
