### ISSUE TITLE
自定义模型测过没？model.cpp里面，addConvolutionNd应该跟类别有关系，但是您的里面是写死的。

### ISSUE THREAD

**Issue by xinsuinizhuan** [xiaocao-tian/yolov8_tensorrt#5]
我看yolov7模型里面，在model.cpp里面，classnum应该是变的：
![图片](https://github.com/xiaocao-tian/yolov8_tensorrt/assets/40679769/85204dcf-5ee4-4a2e-9d4a-e3590acb462a)

但是，我们的里面，都是写死的：
![图片](https://github.com/xiaocao-tian/yolov8_tensorrt/assets/40679769/27dcdbd4-71cc-44c2-acf2-612e7138a91c)

所以，应该自定义模型会崩溃的

**Comment by xiaocao-tian** [comment]
感谢您的提醒，我这个周末调整一下
