### ISSUE TITLE
为什么推理的第一帧耗时很高，之后就正常了，应该如何解决这个问题

### ISSUE THREAD

**Issue by ccqedq** [xiaocao-tian/yolov8_tensorrt#6]
![image](https://github.com/xiaocao-tian/yolov8_tensorrt/assets/37147472/0aa08edf-c955-4cb1-a59b-d7a5b1862b6b)

**Comment by xiaocao-tian** [comment]
您好，据我所知，程序第一次运行都会慢一些，建议您检测时先检测一张无关的图像，然后再检测您需要检测的图像
