### ISSUE TITLE
cmake失败

### ISSUE THREAD

**Issue by ugkjkj** [xiaocao-tian/yolov8_tensorrt#9]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 11.6.targets(790,9): error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64" -x cu   -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -v -g  -D_MBCS -Xcompiler "/EHsc /W0 /nologo /Od /FdDebug\vc143.pdb /FS /Zi /RTC1 /MDd " -o Debug\CMakeCUDACompilerId.cu.obj "C:\Users\陈正\Desktop\新建文件夹\yolov8_tensorrt-main\build\CMakeFiles\3.28.1\CompilerIdCUDA\CMakeCUDACompilerId.cu"”已退出，返回代码为 1。 [C:\Users\陈正\Desktop\新建文件夹\yolov8_tensorrt-main\build\CMakeFiles\3.28.1\CompilerIdCUDA\CompilerIdCUDA.vcxproj]

  

      0 个警告
      1 个错误

**Comment by xiaocao-tian** [comment]
您的电脑用户名是中文吗？ 尝试新建一个英文账号来操作
